name: Pytest
on: [push]
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install development dependencies
        run: pip install 'tasklist[dev]'

      - name: Run pytest
        run: pytest
