name: Pytest
on: [push]
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install development dependencies
        run: pip install '.[dev]'

      - name: Run pytest
        run: pytest
